services:

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: incode-group-username
      MONGO_INITDB_ROOT_PASSWORD: incode-group-password
      MONGO_INITDB_DATABASE: incode-group-test

  incode-group-app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: incode-group-test
      SPRING_DATA_MONGODB_USERNAME: incode-group-username
      SPRING_DATA_MONGODB_PASSWORD: incode-group-password
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
    depends_on:
      - mongodb